# List

In [1]:
a = [2,5, 6, 10]

In [2]:
len(a)

4

# Tuple

In [3]:
a = (2,5,6)

# Set

In [4]:
a = {1,2,3}

In [5]:
a.add(5)

In [6]:
a.add(2)

In [7]:
a

{1, 2, 3, 5}

# Dictionary

In [8]:
a = {"item_1":20, "item_2":"30", "item_3":5}

In [9]:
a

{'item_1': 20, 'item_2': '30', 'item_3': 5}

In [10]:
a["item_2"]

'30'

# Numpy Array

In [11]:
import numpy as np

In [12]:
a = [4,7,8]

In [13]:
a[0] = 10
print(a)

[10, 7, 8]


In [36]:
a = np.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12], [23,14,15,16]])
print(a.shape)
print(a)

(4, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [23 14 15 16]]


In [37]:
s = a.shape
print(s)

(4, 4)


In [38]:
a.dtype

dtype('int64')

# Indexing

In [39]:
a[0,3]

4

In [40]:
a[-1, -1]

16

In [41]:
a[-2]

array([ 9, 10, 11, 12])

# Indexing using conditioning

In [43]:
a > 7

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
a[a > 7]

array([ 8,  9, 10, 11, 12, 23, 14, 15, 16])

In [45]:
a.shape

(4, 4)

In [46]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [23, 14, 15, 16]])

# Slicing

In [47]:
b = a[0, 0:2]
print(b)
print(b.shape)

[1 2]
(2,)


In [49]:
i = 0
c = a[i:i+1,0:2]
print(c)
print(c.shape)

[[1 2]]
(1, 2)


In [50]:
a[ [0,2], [1,2]] 

array([ 2, 11])

# Reshaping

In [51]:
b = a.flatten()
print(b)
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 23 14 15 16]
(16,)


In [52]:
a.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 23, 14, 15, 16]])

In [53]:
a.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [23, 14],
       [15, 16]])

# Broad casting

In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [23, 14, 15, 16]])

In [56]:
a[10:20]

array([], shape=(0, 4), dtype=int64)

In [57]:
ones = np.ones((5,5,3))

In [58]:
ones.shape

(5, 5, 3)

In [59]:
ones[0]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
print(ones[0, 2,1])

1.0


In [61]:
a + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [28, 19, 20, 21]])

In [62]:
a + [1,0,1,0]

array([[ 2,  2,  4,  4],
       [ 6,  6,  8,  8],
       [10, 10, 12, 12],
       [24, 14, 16, 16]])

In [63]:
a + [[1,1,1,0]]

array([[ 2,  3,  4,  4],
       [ 6,  7,  8,  8],
       [10, 11, 12, 12],
       [24, 15, 16, 16]])

# Stacking 

In [64]:
b = np.asarray([[1,2,3,4],
                [0,0,0,0]])

In [65]:
b.shape

(2, 4)

In [66]:
c = np.asarray([[10,10,10,11],[100,100,100,100]])
print(c)
print(c.shape)

[[ 10  10  10  11]
 [100 100 100 100]]
(2, 4)


In [67]:
b = np.hstack([b,c])

In [68]:
b.shape

(2, 8)

In [69]:
b = np.vstack([b,b])

In [70]:
b

array([[  1,   2,   3,   4,  10,  10,  10,  11],
       [  0,   0,   0,   0, 100, 100, 100, 100],
       [  1,   2,   3,   4,  10,  10,  10,  11],
       [  0,   0,   0,   0, 100, 100, 100, 100]])

In [71]:
a = (10,10,5,6)
b = (10,10,5,10)

In [76]:
c = np.concatenate((a,b), axis = 0)

In [77]:
c

array([10, 10,  5,  6, 10, 10,  5, 10])

In [78]:
a = np.asarray([1,2,3,4])
a.shape

(4,)

In [79]:
a = np.asarray([[1],[2],[3],[4]])
a.shape

(4, 1)

In [80]:
# Increase/Decrease Rank

In [81]:
d = np.expand_dims(a, axis=1)

In [82]:
d.shape

(4, 1, 1)

In [83]:
d.squeeze().shape

(4,)