In [3]:
from typing import List
import math
import os
import json


import numpy

In [5]:

a = 30
b = 5

if a > b:
    print(a)
    print(b)
    print("a is larger than b")
else:
    print("b is greater than a")
    
print("This will be printed always")


for i in range(10):
    print(i)

    

30
5
a is larger than b
This will be printed always
0
1
2
3
4
5
6
7
8
9


# List 
1. A list can store differet data types
2. A list is an ordered- a[0], a[5]


In [6]:
import pandas

In [7]:
age = [10, 20, 6]

In [8]:
print(age)

[10, 20, 6]


In [10]:
age[2]

6

# Numpy Array

In [15]:
import numpy as np
import pandas as pd

In [16]:
age_np = np.asarray(age)

In [17]:
type(age)

list

In [18]:
type(age_np)

numpy.ndarray

In [19]:
a = np.asarray([[1,2,3,4,5, 6],
                [2,3,1,0,-1,-1],
                [2,3,1,0,-1,-1]
               ])

In [20]:
a.shape

(3, 6)

In [21]:
a1 = a[0:1,0:5:2]

In [22]:
print(a)

[[ 1  2  3  4  5  6]
 [ 2  3  1  0 -1 -1]
 [ 2  3  1  0 -1 -1]]


In [23]:
print(a1)

[[1 3 5]]
